name: Python tests & coverage

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          # install your package so coverage can find it
          pip install -e .

      - name: Run pytest with coverage
        run: |
          pytest --cov=quactuary --cov-report=xml --cov-report=term

      - name: Test MCP Server
        run: |
          pytest quactuary/tests/test_mcp/
          mcp dev quactuary/mcp/server.py --test-only

      - name: Convert coverage XML to JSON badge
        run: |
          python ./scripts/coverage_to_json.py coverage.xml > coverage.json

      - name: Check version bump against latest Git tag
        run: |
          PKG_VER=$(python -c "from quactuary._version import version; print(version)")
          LATEST_TAG=$(git describe --tags --abbrev=0 | sed 's/^v//')
          echo "Package version: $PKG_VER"
          echo "Latest Git tag: $LATEST_TAG"
          if [ "$PKG_VER" = "$LATEST_TAG" ]; then
            echo "::error::Package version ($PKG_VER) matches latest Git tag. Bump version before publishing."
            exit 1
          fi

      - name: Pull remote main
        run: git pull origin main

      - name: Commit coverage badge JSON
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull: true
          commit_message: "CI: update coverage badge"
          file_pattern: coverage.json
          branch: main
